"""SkyWater sky130 (open_pdk) discovery + a trimmed ngspice model library.

`.lib`-ing the full ``sky130.lib.spice`` parses every device model on each
ngspice launch (~18 s here).  This generator only uses ``nfet_01v8`` and
``pfet_01v8``, so we build an equivalent *trimmed* library that includes just
those two device decks plus the shared parameter/scale infrastructure.  It is
numerically identical to the full library but ~11x faster to load, which makes
the simulation-in-the-loop sizing practical.

Resolution order for the canonical library:
    1. ``$SKY130_LIB``   explicit path to sky130.lib.spice
    2. ``$PDK_ROOT``     open_pdk root containing sky130A/...
    3. ``~/.volare``     default volare install location
"""

from __future__ import annotations

import os
import glob
from dataclasses import dataclass, field

# Device subckt names (open_pdk sky130_fd_pr). Ports: d g s b. Sizes in um.
NFET = "sky130_fd_pr__nfet_01v8"
PFET = "sky130_fd_pr__pfet_01v8"

CORNERS = ["tt", "ss", "ff", "sf", "fs"]


@dataclass
class Pdk:
    orig_lib: str          # canonical sky130.lib.spice
    spice_dir: str         # libs.ref/sky130_fd_pr/spice
    param_dir: str         # libs.tech/ngspice/parameters
    variant: str           # "sky130A" / "sky130B"
    lib_path: str = ""     # library the netlists .lib (set to trimmed lib)

    def __post_init__(self):
        if not self.lib_path:
            self.lib_path = self.orig_lib

    @property
    def corners(self):
        return CORNERS

    def write_fast_lib(self, dest_path: str) -> str:
        """Write a trimmed model library (all corners) and return its path."""
        sections = []
        for c in CORNERS:
            nfet_pm = os.path.join(
                self.spice_dir, f"sky130_fd_pr__nfet_01v8__{c}.pm3.spice")
            pfet_pm = os.path.join(
                self.spice_dir, f"sky130_fd_pr__pfet_01v8__{c}.pm3.spice")
            if not (os.path.isfile(nfet_pm) and os.path.isfile(pfet_pm)):
                continue
            sections.append("\n".join([
                f".lib {c}",
                ".param mc_mm_switch=0",
                ".param mc_pr_switch=0",
                ".option scale=1.0u",
                f'.include "{os.path.join(self.param_dir, "invariant.spice")}"',
                f'.include "{os.path.join(self.param_dir, "lod.spice")}"',
                f'.include "{os.path.join(self.param_dir, "critical.spice")}"',
                f'.include "{os.path.join(self.spice_dir, "sky130_fd_pr__nfet_01v8__mismatch.corner.spice")}"',
                f'.include "{os.path.join(self.spice_dir, "sky130_fd_pr__pfet_01v8__mismatch.corner.spice")}"',
                f'.include "{nfet_pm}"',
                f'.include "{pfet_pm}"',
                f".endl {c}",
            ]))
        header = ("* Trimmed sky130 model library (nfet_01v8 + pfet_01v8 only).\n"
                  "* Numerically identical to sky130.lib.spice for these devices,\n"
                  "* generated by unity_buffer_gen for fast ngspice loading.\n")
        dest_path = os.path.abspath(dest_path)
        os.makedirs(os.path.dirname(dest_path), exist_ok=True)
        with open(dest_path, "w") as fh:
            fh.write(header + "\n\n".join(sections) + "\n")
        return dest_path


def _candidates():
    cands = []
    if os.environ.get("SKY130_LIB"):
        cands.append(os.environ["SKY130_LIB"])
    roots = []
    if os.environ.get("PDK_ROOT"):
        roots.append(os.environ["PDK_ROOT"])
    roots += [os.path.expanduser("~/.volare"),
              "/usr/local/share/pdk", "/foss/pdks"]
    for root in roots:
        patterns = [
            os.path.join(root, "volare", "sky130", "versions", "*", "sky130A",
                         "libs.tech", "ngspice", "sky130.lib.spice"),
            os.path.join(root, "sky130A", "libs.tech", "ngspice",
                         "sky130.lib.spice"),
            os.path.join(root, "**", "sky130A", "libs.tech", "ngspice",
                         "sky130.lib.spice"),
        ]
        for pat in patterns:
            cands.extend(sorted(glob.glob(pat, recursive=True)))
    return cands


def find_pdk(fast_lib_dir: str | None = None) -> Pdk:
    """Locate sky130 and (optionally) build the trimmed library.

    If *fast_lib_dir* is given, the trimmed library is written there and used
    as the netlist library; otherwise the canonical sky130.lib.spice is used.
    """
    for path in _candidates():
        if not (path and os.path.isfile(path)):
            continue
        ng_dir = os.path.dirname(os.path.abspath(path))           # .../ngspice
        variant = ("sky130A" if "sky130A" in path else
                   "sky130B" if "sky130B" in path else "sky130")
        root = path.split(os.sep + variant + os.sep)[0]
        spice_dir = os.path.join(root, variant, "libs.ref",
                                 "sky130_fd_pr", "spice")
        param_dir = os.path.join(ng_dir, "parameters")
        pdk = Pdk(orig_lib=os.path.abspath(path), spice_dir=spice_dir,
                  param_dir=param_dir, variant=variant)
        if fast_lib_dir:
            try:
                pdk.lib_path = pdk.write_fast_lib(
                    os.path.join(fast_lib_dir, "sky130_fast.lib.spice"))
            except OSError:
                pdk.lib_path = pdk.orig_lib
        return pdk
    raise FileNotFoundError(
        "Could not locate sky130.lib.spice. Install the PDK with "
        "`volare enable --pdk sky130 <version>` or set $SKY130_LIB / $PDK_ROOT."
    )
